# Анализ на чувствителността (2)

Определете допустимите граници на промяна на трите ресурса в следната задача:

$$
\begin{align*}
& \max z = 3x_1 + 2x_2 + 5x_3\\
& x_1 + 2x_2 + x_3 \leq 20 \\
& 3x_1 + 2x_3 \leq 30 \\
& x_1 + 4x_2 \leq 40
\end{align*}
$$

Нека да изразим промяната в трите ресурса съответно с $d_1, d_2, d_3$. Тогава първоначалната задача изглежда по следния начин:

$$
\begin{align*}
& \max z = 3x_1 + 2x_2 + 5x_3\\
& x_1 + 2x_2 + x_3 \leq 20 + d_1 \\
& 3x_1 + 2x_3 \leq 30  + d_2 \\
& x_1 + 4x_2 \leq 40 + d_3
\end{align*}
$$

и има каноничен вид:

$$
\begin{align*}
& \max z = 3x_1 + 2x_2 + 5x_3\\
& x_1 + 2x_2 + x_3 + s_1 = 20 + d_1 \\
& 3x_1 + 2x_3 + s_2 = 30  + d_2 \\
& x_1 + 4x_2 + s_3 = 40 + d_3
\end{align*}
$$

Първоначалната симплекс таблица е:

| Таблица 1   |       |            |       |       |       |       |       |       |        |       |       |       |
|------|------|------|------|------|------|------|------|------|------|------|------|------|
|             |       | $C_j$      |       |       |       |       |       |       |        |       |       |       |
| Базисни пр. | $C_B$ | $X_B$      | $x_1$ | $x_2$ | $x_3$ | $s_1$ | $s_2$ | $s_3$ | Съотн. | $d_1$ | $d_2$ | $d_3$ |
| $s_1$       | 0     | 20         | 1     | 2     | 1     | 1     | 0     | 0     |        | 1     | 0     | 0     |
| $s_2$       | 0     | 30         | 3     | 0     | 2     | 0     | 1     | 0     |        | 0     | 1     | 0     |
| $s_3$       | 0     | 40         | 1     | 4     | 0     | 0     | 0     | 1     |        | 0     | 0     | 1     |
| $Z$         |       | $Z_j$      |       |       |       |       |       |       |        |       |       |       |
|             |       | $\Delta_j$ |       |       |       |       |       |       |        |       |       |       |

Таблицата при оптималния план е:

| Таблица опт. |       |            |       |       |       |       |       |       |        |       |       |       |
|------|------|------|------|------|------|------|------|------|------|------|------|------|
|              |       | $C_j$      |       |       |       |       |       |       |        |       |       |       |
| Базисни пр.  | $C_B$ | $X_B$      | $x_1$ | $x_2$ | $x_3$ | $s_1$ | $s_2$ | $s_3$ | Съотн. | $d_1$ | $d_2$ | $d_3$ |
| $x_2$        | 2     | 2.5        | -1/4  | 1     | 0     | 1/2   | -1/4  | 0     |        | 1/2   | -1/4  | 0     |
| $x_3$        | 5     | 15         | 3/2   | 0     | 1     | 0     | 1/2   | 0     |        | 0     | 1/2   | 0     |
| $s_3$        | 0     | 30         | 2     | 0     | 0     | -2    | 1     | 1     |        | -2    | 1     | 1     |
| $Z = 80$     |       | $Z_j$      | 7     | 2     | 5     | 1     | 2     | 0     |        |       |       |       |
|              |       | $\Delta_j$ | 4     | 0     | 0     | 1     | 2     | 0     |        |       |       |       |

Оптималният план е $x_1 = 0, x_2 = 2.5, x_3 = 15, s_1 = 0, s_2 = 0, s_3 = 30$. Кои ресурси са дефицитни? Какви са скритите цени на ресурсите? Ако трябва да се лишим от една единица от втория ресурс, колко допълнителни единици от първия ще са ни нужни, за да запазим една и съща стойност на целевата функция?


Можем да изразим оптималното решение по следния начин:

$$
\begin{align*}
& z = 80 - (-d_1 - 2d_2 - 0 \cdot d3)\\
& x_2 = 2.5 + \frac{1}{2}d_1 - \frac{1}{4}d_2 \\
& x_3 = 15 + \frac{1}{2}d_2 \\
& s_3 = 30 - 2 d_1 + d_2 + d_3
\end{align*}
$$

Настоящото решение остава допустимо, ако всички базисни променливи са неотрицателни, когато варираме наличността на ресурсите.


$$
\begin{align*}
z & = 80 + d_1 + 2d_2 + 0 \cdot d3 \\
x_2 & = 2.5 + \frac{1}{2}d_1 - \frac{1}{4}d_2 \geq 0  \\
x_3 & = 15 + \frac{1}{2}d_2  \geq 0\\
s_3 & = 30 - 2 d_1 + d_2 + d_3 \geq 0
\end{align*}
$${#eq-sens-1}


От целевата функция в [-@eq-sens-1] директно можем да видим скритите цени на ресурсите. От неравенствата в [-@eq-sens-1] можем да изведем граници на допустимата промяна на ресурсите, когато променяме наличността само на един от тях. Ако променяме наличността само на първия ресурс (и не променяме другите два):

$$
\begin{align*}
x_2 & = 2.5 + \frac{1}{2}d_1 \geq 0 \implies d_1 \geq -5 \\
x_3 & = 15 \geq 0 \\
s_3 & = 30 - 2 d_1 \geq 0 \implies d_1 \leq 15
\end{align*}
$$

:::{#exr-sens-1}

Дадена е последната симплекс таблица. Определете алгебрично допустимата промяна на двата ресурса.

| Таблица 3   |       |            |       |       |       |       |     |
|-------------|-------|------------|-------|-------|-------|-------|-----|
|             |       | $C_j$      | 5     | 5     | 0     | 0     |     |
| Базисни пр. | $C_B$ | $X_B$      | $x_1$ | $x_2$ | $s_1$ | $s_2$ |     |
| $x_1$       | 5     | 4          | 1     | 0     | 2/3   | -1/3  |     |
| $x_2$       | 5     | 2          | 0     | 1     | -1/3  | 2/3   |     |
| $Z = 30$    |       | $Z_j$      | 5     | 5     | 1.667 | 1.667 |     |
|             |       | $\Delta_j$ | 0     | 0     | 1.667 | 1.667 |     |

:::

:::{.callout-note collapse="true"}
$$
\begin{align*}
x^* =
\begin{pmatrix}
4 \\ 2 \\ 0 \\ 0
\end{pmatrix}, 
v_1^{*} =
\begin{pmatrix}
2/3 \\
-1/3 \\
0 \\
0 \\
\end{pmatrix} \\
x^* + \epsilon v_1(x^*) \geq 0 \implies \\
\begin{pmatrix}
4 + 2 \epsilon / 3 \\
2 -\epsilon/3 \\
0 \\
0 \\
\end{pmatrix} \geq 0
\end{align*}
$$

От първото неравенство получаваме:

$$
4 + 2 \epsilon / 3 \geq 0 \implies \epsilon \geq -6
$$

От второто неравенство получаваме:

$$
2 - \epsilon / 3 \geq 0 \implies \epsilon \leq 6
$$

Така получаваме границите на допустима промяна $\epsilon \in [-6, 6]$.
:::

:::{#exr-sens-2}

При дадени последни две таблици на симплекс метода, определете допустимите граници на промяна на ресурсите за всички стойности на $\alpha$.

| Таблица 2   |       |            |       |       |       |       |
|-------------|-------|------------|-------|-------|-------|-------|
|             |       | $C_j$      | 2     | 4     | 0     | 0     |
| Базисни пр. | $C_B$ | $X_B$      | $x_1$ | $x_2$ | $s_1$ | $s_2$ |
| $x_2$       | 4     | 5/2        | 1/2   | 1     | 1/2   | 0     |
| $s_2$       | 0     | 3/2        | 1/2   | 0     | -1/2  | 1     |
| $Z$         |       | $Z_j$      | 2     | 4     | 2     | 0     |
|             |       | $\Delta_j$ | 0     | 0     | 2     | 0     |

| Таблица 3   |       |            |       |       |       |       |
|-------------|-------|------------|-------|-------|-------|-------|
|             |       | $C_j$      | 2     | 4     | 0     | 0     |
| Базисни пр. | $C_B$ | $X_B$      | $x_1$ | $x_2$ | $s_1$ | $s_2$ |
| $x_2$       | 4     | 1          | 0     | 1     | 1     | -1    |
| $x_1$       | 2     | 3          | 1     | 0     | -1    | 2     |
| $Z$         |       | $Z_j$      | 2     | 4     | 2     | 0     |
|             |       | $\Delta_j$ | 0     | 0     | 2     | 0     |

:::
:::{.callout-note collapse="true"}
## Решение

Всички оптимални решения са дадени от:

$$
\begin{align*}
x^* = \alpha
\begin{pmatrix}
0 \\
5/2 \\
0 \\
3/2
\end{pmatrix} + (1 -\alpha)
\begin{pmatrix}
3 \\
1 \\
0 \\
0
\end{pmatrix},\quad \alpha \in [0, 1] \\
x^* = \begin{pmatrix}
3(1 - \alpha) \\
7/2 - \alpha \\
0 \\
3/2
\end{pmatrix}
\end{align*}
$$

За втория ресурс претегленото средно от вектор-стълбовете е дадено от:

$$
\begin{align*}
v_1(x^*) =
\alpha \begin{pmatrix}
  0 \\ 1/2 \\ 0 \\ -1/2
\end{pmatrix} +
(1 - \alpha) \begin{pmatrix}
-1 \\ 1 \\ 0 \\ 0
\end{pmatrix} \\
v_1(x^*) = \begin{pmatrix}
\alpha - 1 \\ 1 - \alpha / 2 \\ 0 \\ -\alpha / 2
\end{pmatrix}
\end{align*}
$$

$$
\begin{align*}
x^* + \epsilon v_1(x^*) \geq 0 \implies \\
\begin{pmatrix}
3(1 - \alpha) \\
7/2 - \alpha \\
0 \\
3/2
\end{pmatrix} + \epsilon \begin{pmatrix}
\alpha - 1 \\ 1 - \alpha / 2 \\ 0 \\ -\alpha / 2
\end{pmatrix} \geq 0 \implies \\
\begin{pmatrix}
3(1 - \alpha) + \epsilon  (\alpha - 1) \\
7/2 - \alpha + \epsilon (1 - \alpha / 2) \\
0 \\
3/2 - \epsilon \alpha / 2
\end{pmatrix} \geq 0
\end{align*}
$$

От първото неравенство получаваме за $\alpha \neq 1$.

$$
\begin{align*}
3 - 3\alpha + \epsilon (\alpha - 1) \geq 0\\
\epsilon (\alpha - 1) \geq 3(\alpha - 1) \\
\epsilon \leq 3
\end{align*}
$$

В последната стъпка делим на $1 - \alpha < 0$ и трябва да посоката на неравенството. От последното неравенство получаваме за $\alpha \neq 0$:

$$
\begin{align*}
3/2 - \epsilon \alpha / 2 \geq 0 \\
\epsilon \alpha \leq 3 \\
\epsilon \leq 3 / \alpha
\end{align*}
$$

Третото неравенство е: 

$$
\begin{align*}
7/2 - \alpha + \epsilon (1 - \alpha / 2) \geq 0 \\
\epsilon (1 - \alpha / 2) \geq \alpha - 7/2 \\
\epsilon (2 - \alpha ) \geq 2\alpha - 7 \\
\epsilon \geq \frac{2 \alpha - 7}{2 - \alpha}
\end{align*}
$$
:::

## Пример дуална задача

Дадена е задачата:

$$
\begin{align*}
\min z = -x_2 \\
x_1 - x_2 \leq 1 \\
x_1 + x_2 \leq 4 \\
x_1 - x_2 \geq -1 \\
x_1 \leq 2 \\
x_2 \leq 2 \\
x_1, x_2 \geq 0
\end{align*}
$$

и симплекс таблицата в последната итерация на алгоритъма.

|       |       |                        |       |       |       |       |       |       |       |
|-------|-------|---------|-------|-------|-------|-------|-------|-------|-------|
|       |       | $C_J$                  | 0     | 1     | 0     | 0     | 0     | 0     | 0     |
| B     | $C_B$ | $X_B$                  | $x_1$ | $x_2$ | $s_1$ | $s_2$ | $s_3$ | $s_4$ | $s_5$ |
| $s_1$ | 0     | 2                      | 0     | 0     | 1     | 0     | 1     | 0     | 0     |
| $s_2$ | 0     | 1                      | 0     | 0     | 0     | 1     | 1     | 0     | -2    |
| $x_2$ | 1     | 2                      | 0     | 1     | 0     | 0     | 0     | 0     | 1     |
| $s_4$ | 0     | 1                      | 0     | 0     | 0     | 0     | 1     | 1     | -1    |
| $x_1$ | 0     | 1                      | 1     | 0     | 0     | 0     | -1    | 0     | 1     |
| z     | 2     | $Z_j$                  | 0     | 1     | 0     | 0     | 0     | 0     | 1     |
|       |       | $\Delta_j = Z_j - C_j$ | 0     | 0     | 0     | 0     | 0     | 0     | 1     |

:::{.callout-note collapse="true"}
## Решение

В тази таблица $\Delta_5 = Z_5-C_5=0$ и $s_3$ не е в базиса (т.е. $s_3=0$).

Това сочи, че е възможно да съществува повече от едно оптимално решение. Когато сложим $s_3$ в базиса можем да получим друг оптимум при една и съща стойност на целевата функция.

Трансформираме таблицата в новия базисен вид:

(2) \<- (2)
(3) \<- (1) - (2)
(4) \<- (3)
(5) \<- (4) - (2)
(6) \<- (5) - (2)


|       |       |                        |       |       |       |       |       |       |       |
|-------|-------|---------|-------|-------|-------|-------|-------|-------|-------|
|       |       | $C_J$                  | 0     | 1     | 0     | 0     | 0     | 0     | 0     |
| B     | $C_B$ | $X_B$                  | $x_1$ | $x_2$ | $s_1$ | $s_2$ | $s_3$ | $s_4$ | $s_5$ |
| $s_1$ | 0     | 1                      | 0     | 0     | 1     | -1    | 0     | 0     | 2     |
| $s_3$ | 0     | 1                      | 0     | 0     | 0     | 1     | 1     | 0     | -2    |
| $x_2$ | 1     | 2                      | 0     | 1     | 0     | 0     | 0     | 0     | 1     |
| $s_4$ | 0     | 0                      | 0     | 0     | 0     | -1    | 1     | 1     | 1     |
| $x_1$ | 0     | 2                      | 1     | 0     | 0     | 1     | -1    | 0     | -1    |
| z     | 2     | $Z_j$                  | 0     | 1     | 0     | 0     | 0     | 0     | 1     |
|       |       | $\Delta_j = Z_j - C_j$ | 0     | 0     | 0     | 0     | 0     | 0     | 1     |

:::

## Дуална задача - изродено решение на първичната задача

Дадена е задачата

$$
\begin{align}
& \max z = 3x1 + 2x2 \\
& x1 + x2 \leq 10 \\
& x1 \leq 5 \\
& x2 \leq 5 \\
& x1,x2 \geq 0
\end{align}
$$

Дадени са и таблиците на симплекс алгоритъма

|             |       |                      |       |       |       |       |       |             |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| Iteration-2 |       | $C_j$                | 3     | 2     | 0     | 0     | 0     | $X_B / x_2$ |
| B           | $C_B$ | $X_B$                | $x_1$ | $x_2$ | $s_1$ | $s_2$ | $s_3$ |             |
| $s_1$       | 0     | 5                    | 0     | 1     | 1     | -1    | 0     |             |
| $x_1$       | 3     | 5                    | 1     | 0     | 0     | 1     | 0     |             |
| $s_3$       | 0     | 5                    | 0     | 1     | 0     | 0     | 1     |             |
| z=15        |       | $Z_j$                | 3     | 0     | 0     | 3     | 0     |             |
|             |       | $\Delta = Z_j - C_j$ | 0     | -2    | 0     | 3     | 0     |             |

|                |       |                        |       |       |       |       |       |     |
|--------|--------|---------|--------|--------|--------|--------|--------|--------|
| Iteration-3(1) |       | $C_j$                  | 3     | 2     | 0     | 0     | 0     |     |
| B              | $C_B$ | $X_B$                  | $x_1$ | $x_2$ | $s_1$ | $s_2$ | $s_3$ |     |
| $x_2$          | 2     | 5                      | 0     | 1     | 1     | -1    | 0     |     |
| $x_1$          | 3     | 5                      | 1     | 0     | 0     | 1     | 0     |     |
| $s_3$          | 0     | 0                      | 0     | 1     | -1    | 1     | 1     |     |
| z=15           |       | $Z_j$                  | 3     | 2     | 2     | 1     | 0     |     |
|                |       | $\Delta_j = Z_j - C_j$ | 0     | 0     | 2     | 1     | 0     |     |

|                |       |                        |       |       |       |       |       |     |
|--------|--------|---------|--------|--------|--------|--------|--------|--------|
| Iteration-3(2) |       | $C_j$                  | 3     | 2     | 0     | 0     | 0     |     |
| B              | $C_B$ | $X_B$                  | $x_1$ | $x_2$ | $s_1$ | $s_2$ | $s_3$ |     |
| $s_1$          | 0     | 0                      | \_    | \_    | \_    | \_    | \_    |     |
| $x_1$          | 3     | 5                      | \_    | \_    | \_    | \_    | \_    |     |
| $x_2$          | 2     | 5                      | \_    | \_    | \_    | \_    | \_    |     |
| z=15           |       | $Z_j$                  | \_    | \_    | \_    | \_    | \_    |     |
|                |       | $\Delta_j = Z_j - C_j$ | 0     | 0     | 0     | 3     | 2     |     |
